### PR TITLE
completions: Various shell completion improvements

### PR DESCRIPTION
**Pull request by francislavoie**

### CODE REVIEW

**Comment by mholt** [comment]
> Should we enumerate adapters that aren't plugged-in by default?

This sounds unsustainable -- i.e. very high maintenance.

**Comment by Mohammed90** [comment]
> > Should we enumerate adapters that aren't plugged-in by default?
> 
> This sounds unsustainable -- i.e. very high maintenance.

If we want to be perfectionists, we can hand-edit the generated scripts to pluck the last segment of `﻿caddy.adapters.` listed by the `caddy list-modules` command. I dislike editing generated script though, so not really something I'd go for.

**Comment by mholt** [comment]
The list-modules command only lists the modules that are plugged in, not all the ones that are available.

**Comment by Mohammed90** [comment]
> The list-modules command only lists the modules that are plugged in, not all the ones that are available.

Yes, which is what we want the auto-complete to take values from. It should ideally respect the options available in the executable installed in the system.

**Comment by francislavoie** [comment]
I don't think the list of adapters is really that high maintenance. I just went off the list that's on the site. I don't think there's any harm in just listing all the known ones, it's just autocomplete suggestions. If it doesn't exist, Caddy will tell them right away. No biggie. 

It's also somewhat of a discoverability hint, they might not be aware the others exist and it might make them ask the question, how do I get this adapter?

I like the idea of autofilling them from Caddy though. There's a "command" type. I'll try that out.

👍 For `--pidfile`

**Comment by Mohammed90** [comment]
> I like the idea of autofilling them from Caddy though. There's a "command" type. I'll try that out.

I fiddled with awk and came up with this 😃 

`caddy list-modules | awk '$0 ~ /adapters/ {split($0,a, "."); adapters[length(adapters)+1] = a[3]} END {ads = ""; for (ad in adapters) ads = ads adapters[ad] " "; print ads}'`

**Comment by mholt** [comment]
Oh, yeah, if you only want to show what is installed, then using list-modules is a great idea.

For discoverability, maybe let's wait until the new website is done and plugins can be registered. Then there will be an API...

**Pull request merged**
