### PR TITLE
Add systemd unit file

### PR DESCRIPTION
**Pull request by carlwgeorge**

### CODE REVIEW

**Comment by mholt** [comment]
Alrighty, let's do this!

I like the clean format without comments, as I'd rather people consult the systemd docs directly.

Comments aside, we should compare the differences between this proposal and what @Mohammed90 was working on (this was the last known WIP:

```
[Unit]
Description=Caddy HTTP/2 web server
Documentation=https://caddyserver.com/docs
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service
; Do not allow the process to be restarted in a tight loop. If the
; process fails to start, something critical needs to be fixed.
StartLimitIntervalSec=14400
StartLimitBurst=10

[Service]
Restart=on-abnormal

; User and group the process will run as.
User=www-data
Group=www-data

ExecStart=/usr/local/bin/caddy run -adapter caddyfile -config /etc/caddy/Caddyfile
ExecReload=/usr/local/bin/caddy reload -adapter caddyfile -config /etc/caddy/Caddyfile

; Use graceful shutdown with a reasonable timeout
KillMode=mixed
TimeoutStopSec=5s

; Limit the number of file descriptors; see `man systemd.exec` for more limit settings.
LimitNOFILE=1048576
; Unmodified caddy is not expected to use more than that.
LimitNPROC=512

; Use private /tmp and /var/tmp, which are discarded after caddy stops.
PrivateTmp=true
; Use a minimal /dev (May bring additional security if switched to 'true', but it may not work on Raspberry Pi's or other devices, so it has been disabled in this dist.)
PrivateDevices=true
; Hide /home, /root, and /run/user. Nobody will steal your SSH-keys.
ProtectHome=true
; Make /usr, /boot, /etc and possibly some more folders read-only.
ProtectSystem=full
; … except /var/www/.local/share, because we want Letsencrypt-certificates there.
;   /var/www is $HOME of www-data, and Caddy uses $HOME/.local/share/caddy as storage if $XDG_DATA_HOME isn't set.
;   This merely retains r/w access rights, it does not add any new. Must still be writable on the host!
ReadWritePaths=/var/www/.local/share
ReadWriteDirectories=/var/www/.local/share

; The following additional security directives only work with systemd v229 or later.
; They further restrict privileges that can be gained by caddy. Uncomment if you like.
; Note that you may have to add capabilities required by any plugins in use.
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
```

... and settle on a single best service file.

This is where my own expertise is a bit limited. So, let's discuss it and I'll trust your guys' opinions!

Also, you both have invites to get write access to this repo. Once you accept I'll add Mohammed as a reviewer.

Some things I personally care about:

- Ensuring the dependencies are correct (`after` and `wants`)
- Process restarts are spaced out and limited to only a few restarts every few hours
- Proper permissions / disk access

**Comment by carlwgeorge** [comment]
Diffing the files, without comments:

```diff
-Documentation=https://github.com/caddyserver/caddy/wiki/v2:-Documentation
+Documentation=https://caddyserver.com/docs
```

This PR is set to use the new v2 docs URL.

```diff
-After=network.target
+After=network-online.target
+Wants=network-online.target systemd-networkd-wait-online.service
```

https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

Regarding `Wants`:
> Services using the network should hence simply place an After=network.target dependency in their unit files, and avoid any Wants=network.target or even Requires=network.target.

Regarding `network-online.target`:
> It is strongly recommended not to pull in this target too liberally: for example network server software should generally not pull this in (since server software generally is happy to accept local connections even before any routable network interface is up)

For reference, httpd and nginx in Fedora use `After=network.target`, with no `Wants`.

```diff
+StartLimitIntervalSec=14400
+StartLimitBurst=10
```
```diff
+Restart=on-abnormal
```

I could be mistaken, but I seem to remember Matt saying he doesn't want automatic restarts.

```diff
-User=caddy
-Group=caddy
+User=www-data
+Group=www-data
```

I've always seen httpd use an apache user and nginx use an nginx user.  Following suite, a user named caddy makes the most sense to me here.

```diff
-ExecStartPre=/usr/bin/caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile
```

I'd like to keep this.  If a user accidentally creates an invalid config and tries to restart, this will stop halt on the validation and keep the services running with the previous valid config.

```diff
-ExecStart=/usr/bin/caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
-ExecReload=/usr/bin/caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile
+ExecStart=/usr/local/bin/caddy run -adapter caddyfile -config /etc/caddy/Caddyfile
+ExecReload=/usr/local/bin/caddy reload -adapter caddyfile -config /etc/caddy/Caddyfile
```

Packages should use `/usr/bin/`.  The docs use the double hyphen versions of flags, we should too.

```diff
+KillMode=mixed
```

Per slack conversation, we don't need this since Caddy doesn't spawn children processes.

```diff
```
```diff
```
```diff
```
```diff
```

**Comment by mholt** [comment]
Oh wow, a literal line-by-line diff. すごい 😍 ! And thanks for linking to the docs!

> Regarding Wants:
>
> >Services using the network should hence simply place an After=network.target dependency in their unit files, and avoid any Wants=network.target or even Requires=network.target.
>
> Regarding network-online.target:
>
> >It is strongly recommended not to pull in this target too liberally: for example network server software should generally not pull this in (since server software generally is happy to accept local connections even before any routable network interface is up)
> 
> For reference, httpd and nginx in Fedora use After=network.target, with no Wants.

Caddy does make outbound network requests right away in some cases, and then requires external incoming connections in order to procure TLS certificates at startup. Will a simple `After=network.target` guarantee to work?

If so, then I'm totally fine with that. :+1:

> didn't you say previously that you don't want automatic restarts at all?

Well, Caddy should probably not be automatically restarted if it exits with status code 1: https://caddyserver.com/v1/docs/cli#exit-codes -- do you think systemd with all its complexity can manage that simple task? 😓 

If systemd cannot conditionally employ restart logic, then restarting very calmly with some good pauses between restarts, and not retrying more than a few times in a given period, is an acceptable second place.

No matter what, though, we definitely want to avoid a tight restart loop in every case.

> I've always seen httpd use an apache user and nginx use an nginx user. Following suite, a user named caddy makes the most sense to me here.

Great, `caddy` sounds good to me; I think `www-data` was suggested though because Ubuntu has that by default? @Mohammed90 might know more. (Does a caddy user need to actually exist on the system first?)

> I'd like to keep this. If a user accidentally creates an invalid config and tries to restart, this will halt on the validation and keep the services running with the previous valid config.

Note that all configs are necessarily validated before they are applied. If using the `reload` CLI command to update the config, or if using the API directly, then validation happens anyway: if the new config fails to load, Caddy automatically rolls back to the previously-running config.

Also it's very important that we never shut down the process at any time just to change configuration. There's no need for that. Just something to double-check as we make this file.

> Packages normally use /usr/bin/. The docs use the double hyphen versions of flags, so we should too for consistency.

I support this.

> We don't need this since Caddy doesn't spawn child processes.

I can't guarantee this in the long run though, especially with third-party plugins in the picture. (Still, even if it does spawn child processes, do we need it? If not I'm fine with it being gone.)

> Since this reportedly doesn't work on some systems, I think we should leave it out.

I support this. (We can always add it if we have a specific need/reason to.) Simpler is better.

> With ProtectSystem=full, /var/ is read/write by default, so these lines aren't necessary.

Great

> This only works on systemd 229 and later. CentOS 7 is still a very popular distro, and only has systemd 219. This default unit file should target maximum compatibility. Also, NoNewPrivileges is ignored when PrivateDevices is true, so this setting is pointless if we enable that.

Fair enough. We can always add this later when old distros are out of the picture.

**Comment by mholt** [comment]
Also, where does the output of `stdout` and `stderr` go?

**Comment by carlwgeorge** [comment]
> Will a simple After=network.target guarantee to work?

It only guarantees that the network stack is up.  This should work fine for the default config to start and accept API requests on the admin interface.  Considering systemd's recommendation, I think we should stick with this unless it is shown to be a problem.

If Caddy starts with only localhost and tries to reach out to Letsencrypt, how quickly will it try again?

> Well, Caddy should probably not be automatically restarted if it exits with status code 1

In what scenario would you want Caddy to automatically restart?  Note that services starting at boot is a totally separate thing.  `Restart` is for when the process "exits, is killed, or a timeout is reached".  I'd recommend against setting a restart at all.  If Caddy exits like this, the user should investigate.  If you insist on it, the logic is documented.

https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=interval

(`Restart` defaults to no, `StartLimitIntervalSec` defaults to 10s, and `StartLimitBurst` defaults to 5.)

> think www-data was suggested though because Ubuntu has that by default? 

Yes, it's something they get from Debian.

https://wiki.debian.org/Apache#FAQ

Outside of Debian and Ubuntu, it's much more common to name the user after the application.

> Does a caddy user need to actually exist on the system first?

Systemd has a really cool `DynamicUser` feature, but it requires at least version 235.  That version isn't very widespread yet, so the RPM creates that user during installation.

http://0pointer.net/blog/dynamic-users-with-systemd.html

> Note that all configs are necessarily validated before they are applied.

Cool!  Then we don't need `ExecStartPre`.

> I can't guarantee this in the long run though, especially with third-party plugins in the picture. 

By default, when a unit is stopped a SIGTERM is sent to all process in the control group (including child processes).  Any processes in the control group that still exist after 90s are sent a SIGKILL.  Switching `KillMode` to mixed means that the initial SIGTERM is only sent to the main process, which is expected to tell it's children to exit.  The SIGKILL is still sent to all remaining process in the control group after the 90s timeout.

> Also, where does the output of stdout and stderr go?

They are logged to the journal.

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardOutput=
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardError=

**Comment by mholt** [comment]
> It only guarantees that the network stack is up. This should work fine for the default config to start and accept API requests on the admin interface. Considering systemd's recommendation, I think we should stick with this unless it is shown to be a problem.
>
> If Caddy starts with only localhost and tries to reach out to Letsencrypt, how quickly will it try again?

It's exponential backoff... so, it might be fine, but it seems unnecessary to even try starting the server before the network is online. I'm willing to try it as-is but we should be prepared to change it...

> In what scenario would you want Caddy to automatically restart? Note that services starting at boot is a totally separate thing. Restart is for when the process "exits, is killed, or a timeout is reached". I'd recommend against setting a restart at all. If Caddy exits like this, the user should investigate. If you insist on it, the logic is documented.

For example, if there's a rogue/buggy plugin that causes the main goroutine to panic on some unlikely condition 17 days after starting, then the process should be restarted to keep sites online.

> Outside of Debian and Ubuntu, it's much more common to name the user after the application.

Okay; @Mohammed90 do you think it's OK to use the `caddy` username instead of `www-data`, for consistency?

> Systemd has a really cool DynamicUser feature, but it requires at least version 235. That version isn't very widespread yet, so the RPM creates that user during installation.

Ah, that's good to know. @Mohammed90 I'll leave it up to what you think is best as far as the user for Debian/Ubuntu goes, then.

> By default, when a unit is stopped a SIGTERM is sent to all process in the control group (including child processes). Any processes in the control group that still exist after 90s are sent a SIGKILL. Switching KillMode to mixed means that the initial SIGTERM is only sent to the main process, which is expected to tell it's children to exit. The SIGKILL is still sent to all remaining process in the control group after the 90s timeout.

I see! In that case, I'll leave it to your best judgment since I think either is fine; simpler is probably better though (i.e. remove it if you feel comfortable/good with that).

> They are logged to the journal.

Okay, that's a fine default.

--------------------------

@carlwgeorge Great, I'll do one more review and we'll go from there!

**Comment by carlwgeorge** [comment]
Just tested this on CentOS 7 and Fedora 31, from the copr packages.  It all works as intended.

**Comment by Conan-Kudo** [comment]
If I remember correctly, systemd units that have "unknown" stanzas will just have those lines ignored by systemd. So it should be possible to include stanzas for features in newer versions of systemd without breaking old ones. @carlwgeorge, could you check to see if that's still true?

**Comment by Mohammed90** [comment]
LGTM. I mean it's clear @carlwgeorge knows more about systemd than me 😄 I mean, he broke down every stanza with reasoning for why or why-not.

Just note, this can serve as good template providing safe defaults for wider audience with variety of devices/distros. We have more control on the image we create for DigitalOcean (Ubuntu 18.04, systemd 237), so we can fine-tune the config further (e.g. PrivateDevices) and not worry about their limitations. How does that sound?

I remember learning briefly about DynamicUser, but never got my hands dirty with it. Given its benefits, we can probably make use of it as safe-default for the DigitalOcean image.

**Comment by carlwgeorge** [comment]
> If I remember correctly, systemd units that have "unknown" stanzas will just have those lines ignored by systemd.

Yes, this is still true, but since the stated goal is simple then it's probably better to leave out optional directives that may or may not take effect.  Systemd drop-ins make it trivial for users to add things like this if they want it.

> I mean it's clear @carlwgeorge knows more about systemd than me

Nah, I just know where to find the docs.  :grin:  Took me a little bit of time to research all of those differences and make a recommendation on each.

**Pull request merged**
