### PR TITLE
modules: Add manpages module

### PR DESCRIPTION
**Pull request by pymnh**
Closes https://github.com/caddyserver/dist/issues/29

Thought it makes sense if this goes into `modules/manpages/` so that `manpages/` is free for the actual rendered man pages

Is `caddy-manpages` an apropriate module ID? or rather only `manpages`?

As mentioned I am rather new to Go: So since this depends on `caddycmd.Commands()` I understand once caddyserver/caddy#4316 gets merged I'll update the go.mod and go.sum files to point to the according commit

### CODE REVIEW

**Comment by pymnh** [comment]
I polished the template a bit and added some comments explaining what it does.

one caveat:
Possible arguments to flags (like `<string>`, `<path>`, nothing) are documented in the upper part of the template (chapter synopsis), but not in the paragraph listing each flag and its usage (options), as you can see [here](https://htmlpreview.github.io/?https://gist.githubusercontent.com/pymnh/58169a08c124c7267506b7854d36ddda/raw/da10c2b4b2d1b1ec214a18f8af0985afb0c0216f/caddy-run.1.NEW.html)). This is because the template will iterate through `*.flag.Flag`, but arguments to flags are hardcoded per subcommand in `Command.Usage`. 

Probably doable to add a helper function that parses `Command.Usage` for pairs of flags and their possible arguments. For my own scripts I wrote in the past dealing with strings usually added complexity and breaks in unexpected ways, so I'd like your optionion before attempting that.

**Comment by francislavoie** [comment]
Sorry for having left this hanging.

@carlwgeorge as the one who opened the original request (in 2017! 😬) do you have any comments/feedback on this? Does it look satisfactory to you? Good enough to include in the COPR builds?

**Review by francislavoie — APPROVED** [review]

**Comment by mohammed90** [comment]
Since we switched to using spf13/cobra in caddyserver/caddy#4565, the manpage generation is automatically provided by Cobra. The missing step is to amend the package installation scripts to use the command to place the files in the right place. Thank you for the effort you put into this PR!

**Comment by francislavoie** [comment]
I second that - thanks for the effort @pymnh!

We have a better, more automated approach built into Caddy now, so this is obsolete.

**Pull request closed without merging**
