### PR TITLE
init: add --force to ExecReload

### PR DESCRIPTION
**Pull request by jian-lin**
This caddy commit[1] adds --force flag, which helps to reload tls
certificates from disk when the config does not change.

This patch add this flag to ExecReload so that we can get this benefit
when using systemctl reload.

[1]: https://github.com/caddyserver/caddy/commit/2772ede43c852fa50f3527dbd94ae747b6f64365

### CODE REVIEW

**Comment by mholt** [comment]
Hmm, is there a way to set that flag on the systemctl command? It would be unfortunate if every reload always was forced even if not necessary or intentional...

**Comment by jian-lin** [comment]
> is there a way to set that flag on the systemctl command

I don't think so.

My use case is that when my acme cert is renewed, the acme service runs `systemctl try-reload-or-restart caddy.service` to try to let caddy use the new cert. Without `--force`, caddy stills uses the old cert.

> It would be unfortunate if every reload always was forced even if not necessary or intentional

I agree if the cost is not small.

**Comment by francislavoie** [comment]
Why aren't you using Caddy for ACME instead?

**Comment by jian-lin** [comment]
Well, that's a cert for my email server. Currently, I use lego and caddy together to manage that cert. It seems that if only caddy is used, it's not easy to notify my email server when the cert is renewed.

**Comment by jian-lin** [comment]
I admit it's not a common use case and I am fine if you close this pr.

**Comment by mholt** [comment]
I'm probably ok with merging it. I don't think it'll cause a problem for most users. Maybe none at all!

**Review by mholt — APPROVED** [review]
Let's go ahead and try this. If we get (enough, or serious enough) complaints, we can revert; but I think it makes sense that if you explicitly tell the service to reload, to always reload, not just "try" to reload. If you call `caddy reload` directly then you can customize the flags.

**Comment by francislavoie** [comment]
FWIW, you can also override the systemd service if necessary: https://caddyserver.com/docs/running#overrides

**Comment by mholt** [comment]
Yeah, and maybe that's better. We'll find out, based on feedback we get in the future.

**Comment by jian-lin** [comment]
> FWIW, you can also override the systemd service if necessary

Yeah, I know that. Thanks.
I make this pr because I think the community may benefit from it.

**Pull request merged**
