### PR TITLE
Add German and Dutch congratulations

### PR DESCRIPTION
**Pull request by Firesphere**

### CODE REVIEW

**Comment by mholt** [comment]
I was hoping to keep them fitting on just a single line so I just chose some languages randomly. Does it look weird to you to have a line break?

**Comment by Firesphere** [comment]
It stayed on one line for me, unless I size my screen down.
So, to me, it is fine, but that's on a 2k screen. I guess it's your pick :)

**Comment by Firesphere** [comment]
I see what you mean on smaller screens.
Here's an idea...
What if, there are a lot of translations, but all are hidden (maybe except Ukranian, because, you know, support Ukraine!)
And a subset of the others are made visible at random?
Probably with a very 3-line javascript, that removes the "hidden" class from `h1 span.hidden`?

**Comment by mholt** [comment]
I don't know. It's not that big of a deal if it wraps. I probably would rather do that than have it be complex.

One stupid request, could we move the new languages to the end? I don't know a better, fairer way to sort them :stuck_out_tongue:

**Comment by mholt** [comment]
Thanks!

**Pull request merged**
