### PR TITLE
new version

### PR DESCRIPTION
**Pull request by shibumi**
bump to version 15.

### CODE REVIEW

**Comment by francislavoie** [comment]
@shibumi FYI there's a reverse_proxy regression in beta15, see the release notes (unix sockets as the address is broken, fixed in `v2` branch though). Just in case you weren't aware

**Comment by shibumi** [comment]
@francislavoie thanks, do you have a patch for it?

**Comment by francislavoie** [comment]
Yeah it's fixed as of https://github.com/caddyserver/caddy/commit/c83d40ccd43c8692061732974bd02fb388acd425

**Comment by shibumi** [comment]
@francislavoie thanks!

**Pull request merged**
