### PR TITLE
deb: Add caddy user to www-data group if it exists

### PR DESCRIPTION
**Pull request by francislavoie**
Didn't try it via a .deb yet but trying those exact commands locally:

```
$ getent group www-data
www-data:x:33:francis

$ getent group www-data >/dev/null && echo $?
0

$ sudo usermod -aG www-data caddy
[sudo] password for francis:

$ getent group www-data
www-data:x:33:francis,caddy
```

Should do what we need 👍

### CODE REVIEW

**Comment by Mohammed90** [comment]
Am I missing something? This changes the permission on the shell-completion generation script (scripts/completions/generate.sh) from 755 to 644, which yeah that'd be better file perms but perhaps wrong PR 😄

**Comment by mholt** [comment]
Yeah I see 0 changes except a permission change.

**Comment by francislavoie** [comment]
Wat

Sorry 🤦‍♂️

One moment please...

**Comment by francislavoie** [comment]
Okay sorry lmao

I switched branches and didn't pop the stash, had that other permissions change stick around though, somehow... which I never even did myself. But anyways, 755 is correct (need the `+x` on the shell script)

**Pull request merged**
