### PR TITLE
Update to beta8

### PR DESCRIPTION
**Pull request by carlwgeorge**

### CODE REVIEW

**Comment by mholt** [comment]
Actually, maybe hold out on this one, I discovered a critical bug just after tagging it, that makes all HTTP requests panic 😅 oops. Maybe I will release beta 8 today as a hotfix.

**Comment by carlwgeorge** [comment]
Beta8 has been built in copr now.

https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/build/1085490/

**Comment by mholt** [comment]
Great!

Beta 9 should be coming out soon. How should we go about automating this for new releases?

**Comment by carlwgeorge** [comment]
I'm still research the options for automation with copr.  For now I don't mind triggering the builds manually.

**Pull request merged**
